In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Mari\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [3]:
df.index.name = 'job_index'

In [4]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [5]:
df.index.dtype

dtype('int64')

# reset_index()

In [6]:
df_ukr = df[df['job_country']=="Ukraine"]

df_ukr.reset_index(inplace = True)

df_ukr

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,275,Data Engineer,Інженер з договірної роботи,"Dnipro, Dnipropetrovsk Oblast, Ukraine",via RABOTA.ua,Full-time,False,Ukraine,2023-01-24 13:51:43,True,False,Ukraine,NaN,NaN,NaN,Vodafone Україна,NaN,NaN
1,524,Data Analyst,Data analyst,"Kyiv, Ukraine",via Robota.ua,Full-time,False,Ukraine,2023-07-11 13:47:33,True,False,Ukraine,NaN,NaN,NaN,"Fozzy Group, Логістика",NaN,NaN
2,655,Data Engineer,Middle Data Engineer (Communication Management...,"Chernivtsi, Chernivtsi Oblast, Ukraine",via Rabota.ua,Full-time,False,Ukraine,2023-06-02 13:43:32,True,False,Ukraine,NaN,NaN,NaN,Sigma Software,NaN,NaN
3,855,Data Scientist,Data Scientist (Machine Learning),"Kyiv, Ukraine",via Robota.ua,Full-time,False,Ukraine,2023-09-15 13:47:48,False,False,Ukraine,NaN,NaN,NaN,"ФОРА, ООО",NaN,NaN
4,914,Senior Data Scientist,Senior Certification Manager - Data Science,Anywhere,via Levels.fyi,Contractor,True,Ukraine,2023-11-22 13:55:12,False,False,Ukraine,NaN,NaN,NaN,DataCamp,"['r', 'python', 'sql']","{'programming': ['r', 'python', 'sql']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900,780162,Software Engineer,Python Developer,"Kyiv, Ukraine",via Startup Jobs,Full-time,False,Ukraine,2023-08-04 05:16:45,True,False,Ukraine,NaN,NaN,NaN,Neo Cybernetica,"['python', 'rust', 'javascript', 'typescript',...","{'analyst_tools': ['datarobot'], 'libraries': ..."
1901,780577,Software Engineer,Senior Software Engineer,"Lviv, Lviv Oblast, Ukraine",via BeBee Україна,Full-time,False,Ukraine,2023-09-01 05:56:00,True,False,Ukraine,NaN,NaN,NaN,Hitachi Careers,"['shell', 'bash', 'linux']","{'os': ['linux'], 'programming': ['shell', 'ba..."
1902,780594,Software Engineer,Software Engineer,"Kyiv, Ukraine",via BeBee Україна,Full-time,False,Ukraine,2023-09-03 06:03:49,False,False,Ukraine,NaN,NaN,NaN,Hitachi Careers,"['c', 'linux']","{'os': ['linux'], 'programming': ['c']}"
1903,781080,Data Analyst,Team Lead Supply Chain Data Analyst,"Odesa, Odesa Oblast, Ukraine",via LinkedIn,Full-time,False,Ukraine,2023-09-25 06:17:44,False,False,Ukraine,NaN,NaN,NaN,AUTODOC,"['sql', 'python', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
1904,782549,Data Analyst,Middle Data Analyst,"Kyiv, Ukraine",via Вакансии Trabajo.org,Full-time,False,Ukraine,2023-05-28 06:21:24,True,False,Ukraine,NaN,NaN,NaN,Genesis,['tableau'],{'analyst_tools': ['tableau']}

# set_index()

In [7]:
df_ukr.set_index('job_index', inplace = True)

In [8]:
df_ukr

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
275,Data Engineer,Інженер з договірної роботи,"Dnipro, Dnipropetrovsk Oblast, Ukraine",via RABOTA.ua,Full-time,False,Ukraine,2023-01-24 13:51:43,True,False,Ukraine,NaN,NaN,NaN,Vodafone Україна,NaN,NaN
524,Data Analyst,Data analyst,"Kyiv, Ukraine",via Robota.ua,Full-time,False,Ukraine,2023-07-11 13:47:33,True,False,Ukraine,NaN,NaN,NaN,"Fozzy Group, Логістика",NaN,NaN
655,Data Engineer,Middle Data Engineer (Communication Management...,"Chernivtsi, Chernivtsi Oblast, Ukraine",via Rabota.ua,Full-time,False,Ukraine,2023-06-02 13:43:32,True,False,Ukraine,NaN,NaN,NaN,Sigma Software,NaN,NaN
855,Data Scientist,Data Scientist (Machine Learning),"Kyiv, Ukraine",via Robota.ua,Full-time,False,Ukraine,2023-09-15 13:47:48,False,False,Ukraine,NaN,NaN,NaN,"ФОРА, ООО",NaN,NaN
914,Senior Data Scientist,Senior Certification Manager - Data Science,Anywhere,via Levels.fyi,Contractor,True,Ukraine,2023-11-22 13:55:12,False,False,Ukraine,NaN,NaN,NaN,DataCamp,"['r', 'python', 'sql']","{'programming': ['r', 'python', 'sql']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780162,Software Engineer,Python Developer,"Kyiv, Ukraine",via Startup Jobs,Full-time,False,Ukraine,2023-08-04 05:16:45,True,False,Ukraine,NaN,NaN,NaN,Neo Cybernetica,"['python', 'rust', 'javascript', 'typescript',...","{'analyst_tools': ['datarobot'], 'libraries': ..."
780577,Software Engineer,Senior Software Engineer,"Lviv, Lviv Oblast, Ukraine",via BeBee Україна,Full-time,False,Ukraine,2023-09-01 05:56:00,True,False,Ukraine,NaN,NaN,NaN,Hitachi Careers,"['shell', 'bash', 'linux']","{'os': ['linux'], 'programming': ['shell', 'ba..."
780594,Software Engineer,Software Engineer,"Kyiv, Ukraine",via BeBee Україна,Full-time,False,Ukraine,2023-09-03 06:03:49,False,False,Ukraine,NaN,NaN,NaN,Hitachi Careers,"['c', 'linux']","{'os': ['linux'], 'programming': ['c']}"
781080,Data Analyst,Team Lead Supply Chain Data Analyst,"Odesa, Odesa Oblast, Ukraine",via LinkedIn,Full-time,False,Ukraine,2023-09-25 06:17:44,False,False,Ukraine,NaN,NaN,NaN,AUTODOC,"['sql', 'python', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
782549,Data Analyst,Middle Data Analyst,"Kyiv, Ukraine",via Вакансии Trabajo.org,Full-time,False,Ukraine,2023-05-28 06:21:24,True,False,Ukraine,NaN,NaN,NaN,Genesis,['tableau'],{'analyst_tools': ['tableau']}

# sort_index()

In [9]:
median_pivot = df_ukr.pivot_table(values = 'salary_year_avg', index = 'job_title_short', aggfunc = ['median', 'min', 'max'])

In [10]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  72900.0         72900.0         72900.0
Cloud Engineer                    89100.0         89100.0         89100.0
Data Analyst                      72900.0         53014.0        111175.0
Data Engineer                     89100.0         50500.0        147500.0
Data Scientist                   131846.5         43200.0        157500.0
Machine Learning Engineer         89100.0         65000.0        141000.0
Senior Data Engineer              96773.0         96773.0         96773.0
Senior Data Scientist            157500.0        157500.0        157500.0
Software Engineer                 54000.0         54000.0         54000.0

In [16]:
median_pivot.sort_values(by = ('median', 'salary_year_avg'), ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            157500.0        157500.0        157500.0
Data Scientist                   131846.5         43200.0        157500.0
Senior Data Engineer              96773.0         96773.0         96773.0
Machine Learning Engineer         89100.0         65000.0        141000.0
Cloud Engineer                    89100.0         89100.0         89100.0
Data Engineer                     89100.0         50500.0        147500.0
Business Analyst                  72900.0         72900.0         72900.0
Data Analyst                      72900.0         53014.0        111175.0
Software Engineer                 54000.0         54000.0         54000.0

In [19]:
median_pivot.sort_index(inplace=True)
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  72900.0         72900.0         72900.0
Cloud Engineer                    89100.0         89100.0         89100.0
Data Analyst                      72900.0         53014.0        111175.0
Data Engineer                     89100.0         50500.0        147500.0
Data Scientist                   131846.5         43200.0        157500.0
Machine Learning Engineer         89100.0         65000.0        141000.0
Senior Data Engineer              96773.0         96773.0         96773.0
Senior Data Scientist            157500.0        157500.0        157500.0
Software Engineer                 54000.0         54000.0         54000.0